## Numpy<br />

In [1]:
import numpy as np

## 创建数组

In [4]:
np_array = np.array([1,2,3,4,5])
print(np_array)
print("维度：",np_array.ndim)
print("大小：",np_array.shape)
print("类型：",np_array.dtype)
np_array = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(np_array)
print("维度：",np_array.ndim)
print("大小：",np_array.shape)
print("类型：",np_array.dtype)
np_array = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(np_array)
print("维度：",np_array.ndim)
print("大小：",np_array.shape)
print("类型：",np_array.dtype)

[1 2 3 4 5]
维度： 1
大小： (5,)
类型： int32
[[1 2 3 4 5]
 [1 2 3 4 5]]
维度： 2
大小： (2, 5)
类型： int32
[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]
维度： 3
大小： (2, 2, 5)
类型： int32


## 初始化函数

In [19]:

zero_array = np.zeros(2)
ones_array = np.ones((2,3))
rand_array = np.random.rand(2,3)
print(zero_array)
print(ones_array)
print(rand_array)

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.46911906 0.63382825 0.29113067]
 [0.58818429 0.28850973 0.95267172]]


In [25]:
data = np.arange(10)
print(data)
reshape = data.reshape((2,5))
print(reshape)
print(reshape.dtype)
reshape = reshape.astype(float)
print(reshape.dtype)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
int32
float64


## 索引与切片

In [33]:
data = np.arange(9)
print(data)
print(data[:2])
print(data[2:])

[0 1 2 3 4 5 6 7 8]
[0 1]
[2 3 4 5 6 7 8]


In [37]:
# 多维数组切片时先行后列
data = data.reshape(3,3)
print(data)
print(data[:2,1:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]]


In [43]:
data = np.arange(27).reshape(3,3,3)
print(data)
print(data[1,:2,1:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[10 11]
 [13 14]]


In [49]:
data = np.arange(9).reshape(3,3)
print(data > 4)
print(data[data>4])

[[False False False]
 [False False  True]
 [ True  True  True]]
[5 6 7 8]


In [52]:
data = np.arange(9).reshape(3,3)
print(data)
print(data.transpose)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
<built-in method transpose of numpy.ndarray object at 0x000001EFE42BF580>
