# 第1节 Numpy使用




In [3]:
import numpy as np

## 1、创建数组

* ndim, shape和dtype属性

In [4]:
# 一维数组
l = [1, 2, 3, 4, 5, 6]
data = np.array(l)
print(data)

print('维度个数', data.ndim)
print('各维度大小: ', data.shape)
print('数据类型: ', data.dtype)

[1 2 3 4 5 6]
维度个数 1
各维度大小:  (6,)
数据类型:  int32


In [5]:
# 二维数组
l = [[1., 2., 3.], [4., 5., 6.]]
data = np.array(l)
print(data)

print('维度个数', data.ndim)
print('各维度大小: ', data.shape)
print('数据类型: ', data.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
维度个数 2
各维度大小:  (2, 3)
数据类型:  float64


In [6]:
# 三维数组
l = [
        [
            [1, 2], 
            [3, 4]
        ], 
        [
            [5, 6], 
            [7, 8]
        ]
]
data = np.array(l)
print(data)

print('维度个数', data.ndim)
print('各维度大小: ', data.shape)
print('数据类型: ', data.dtype)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
维度个数 3
各维度大小:  (2, 2, 2)
数据类型:  int32


# 2、初始化函数
* np.zeros(), np.ones(), np.random.rand()

In [7]:
# np.zeros()
zeros_arr = np.zeros((3, 4))

# np.ones()
ones_arr = np.ones((2, 3))

# np.random.rand()
# 注意传入的参数和之前的不同
rand_arr = np.random.rand(4, 5)

print(zeros_arr)
print()
print(ones_arr)
print()
print(rand_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[0.64677415 0.15091922 0.18527562 0.19827004 0.77882644]
 [0.35992332 0.41157305 0.70556356 0.98161692 0.98608212]
 [0.40101196 0.69691979 0.74778989 0.05023874 0.40690009]
 [0.70440298 0.97627615 0.69402449 0.10748103 0.29844251]]


* np.arange()

In [42]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


* reshape()

In [7]:
arr2 = arr.reshape((5, 2))
print(arr2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* astype()

In [43]:
print(arr2.dtype)
arr3 = arr2.astype(float)
print(arr3.dtype)

int32
float64


# 3、多维数组的操作

* 索引与切片

In [45]:
# 一维数组索引
l = [1, 2, 3, 4, 5, 6]
data = np.array(l)
print(data)
print(l[0])
print(l[-1])
print(l[3:])

[1 2 3 4 5 6]
1
6
[4, 5, 6]


In [46]:
# 多维数组索引
data = np.arange(9).reshape(3, 3)
print(data)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
print(data[:2, 1:])

[[1 2]
 [4 5]]


In [48]:
a = [1,2,3,4,5]
print(a)
a[:3]

[1, 2, 3, 4, 5]


[1, 2, 3]

In [50]:
print(data[2])
print(data[2, :])
print(data[2:, :])

[6 7 8]
[6 7 8]
[[6 7 8]]


In [51]:
print(data[:, :2])

[[0 1]
 [3 4]
 [6 7]]


In [52]:
print(data[1, :2])
print(data[1:2, :2])

[3 4]
[[3 4]]


In [53]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
is_gt = data > 4
print(is_gt)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [16]:
print(data[is_gt])

[5 6 7 8]


In [17]:
print(data[data > 4])

[5 6 7 8]


In [55]:
# 找出数据中大于4的偶数
print(data[ (data > 4) & (data % 2 == 0)])

[6 8]


* 转置

In [56]:
data = np.arange(15).reshape(3, 5)
print(data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [57]:
print(data.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [58]:
print(np.transpose(data))

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [59]:
print(np.swapaxes(data, 0, 1))

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


# 4、函数

In [68]:
data = np.arange(10).reshape(5, 2)
print(data)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [69]:
print(np.mean(data))
print(np.mean(data, axis=0))
print(np.mean(data, axis=1))

4.5
[4. 5.]
[0.5 2.5 4.5 6.5 8.5]


In [70]:
print(np.sum(data))
print(np.sum(data, axis=0))
print(np.sum(data, axis=1))

45
[20 25]
[ 1  5  9 13 17]


In [71]:
print(np.max(data))
print(np.max(data, axis=0))
print(np.max(data, axis=1))

9
[8 9]
[1 3 5 7 9]


In [72]:
print(np.std(data))
print(np.var(data))

2.8722813232690143
8.25


In [73]:
print(np.argmax(data))
print(np.argmax(data, axis=0))
print(np.argmax(data, axis=1))

9
[4 4]
[1 1 1 1 1]


In [75]:
print(np.any(data > 5))

True


In [76]:
print(np.all(data > 5))

False


In [77]:
arr = np.array([[1, 2, 1], [2, 3, 4]])
print(arr)
print(np.unique(arr))

[[1 2 1]
 [2 3 4]]
[1 2 3 4]


# 5、向量化

In [82]:
# a = [a1,a2,a3], b = [b1,b2,b3] => a1*b1+a2*b2+a3*b3
a = np.arange(100000, dtype=float)
b = np.arange(100000, 0, -1, dtype=float)

In [84]:
# 未使用向量化
import time

begin = time.time()
results = []
for i, j in zip(a, b):
    results.append(i * j)
end = time.time()
print('运行时间：', end - begin)

运行时间： 0.024859905242919922


In [85]:
# 使用向量化
begin = time.time()
results = a * b
end = time.time()
print('运行时间：', end - begin)

运行时间： 0.001995086669921875
